jsrepojs/jsrepo

.changeset/little-seals-repair.md, package.json, src/commands/add.ts, src/commands/index.ts
This should help debug issues on publish.
=> feat: Add verbose flag for troubleshooting

.changeset/khaki-queens-worry.md, .changeset/quiet-glasses-wink.md, package.json, pnpm-lock.yaml, src/commands/add.ts
=> Improves verbose logging and makes blocks required

.changeset/healthy-hats-matter.md, blocks/types/result.ts, package.json, pnpm-lock.yaml
This just saves you internally from allowing the result from being modified and makes no changes to the api.
=> Make internal result readonly

.changeset/bright-poems-care.md, README.md, package.json, src/commands/test.ts
=> feat: Add ability to tests all of your installed blocks without specifying each block

.changeset/flat-badgers-swim.md, README.md, package.json
Also improves project description.
=> chore: Update readme to include links to docs

.changeset/red-rabbits-help.md, README.md, blocks/utilities/is-number.test.ts, blocks/utilities/is-number.ts, package.json, pnpm-lock.yaml, src/blocks.ts
Adds `isNumber` block with documentation and testing.
=> feat: `isNumber` block

.changeset/friendly-timers-repeat.md, .changeset/pre.json, .changeset/shiny-dodos-battle.md, package.json, schema.json, src/commands/add.ts, src/commands/init.ts, src/config/index.ts, src/utils/git-providers.ts
Allows you to supply multiple repos to the config file. The add command will list blocks from every repo.
=> feat: Mutliple config repos

.changeset/hip-rivers-swim.md, .changeset/pre.json, package.json, src/commands/add.ts, src/commands/test.ts
Now the test command can pull and run tests from remote repositories.
=> fix: fix `test` command

.changeset/neat-rockets-build.md, .changeset/pre.json, README.md, package.json, schema.json, src/commands/build.ts
- update README.md
- Improve schema documentation
- Fix some wording in `build` help
=> feat: new documentation

.changeset/brown-phones-know.md, .changeset/kind-eels-rescue.md, .changeset/mean-owls-arrive.md, .changeset/polite-ligers-float.md, .github/workflows/ci.yml, .gitignore, blocks.json, package.json, pnpm-lock.yaml, schema.json, src/blocks/types/result.ts, src/commands/add.ts, src/commands/build.ts, src/commands/init.ts, src/commands/test.ts, src/config/index.ts, src/utils/get-installed-blocks.ts, src/utils/git-providers.ts, src/utils/index.ts, src/utils/prompts.ts, tests/git-providers.test.ts
- Gets rid of support for index.ts
- Adds shorthand adding for blocks like `github/ieedan/std/utilities/sleep`
- Adds support for multiple repos with the same categories and block names
- Adds multiple-repo support for `test` command
- Adds tags support for github allowing you to do `github/ieedan/std/tree/v0.0.1`
=> feat: More next features

.changeset/pre.json, .changeset/thick-eggs-roll.md, .changeset/tidy-queens-suffer.md, README.md, blocks.json, package.json, src/commands/add.ts, src/commands/init.ts, src/commands/test.ts, src/config/index.ts
Init command now runs the prompts and defaults to the current config values.
=> feat: init rememeber config

.changeset/fast-tips-grow.md, .changeset/pre.json, package.json, pnpm-lock.yaml, src/blocks/types/result.ts, src/blocks/utilities/array-sum.ts, src/blocks/utilities/lines.ts, src/blocks/utilities/pad.ts, src/commands/add.ts, src/commands/diff.ts, src/commands/index.ts, src/commands/test.ts, src/index.ts, src/utils/get-installed-blocks.ts, src/utils/git-providers.ts
The diff command will allow you to check for remote changes and see them as a diff in the CLI.
I spent a lot of time making this nice to work with adding collapsing for unchanged blocks etc.
=> feat: Add `diff` command

.changeset/neat-moons-sparkle.md, .changeset/pre.json, package.json, src/blocks/utilities/map-to-array.ts, src/blocks/utilities/pad.ts, src/blocks/utilities/strip-ansi.ts, src/commands/add.ts
If you selected a block and a block that depended on that block it would add the block twice.
=> fix: repeat adds of the same block when

.changeset/pre.json, .changeset/proud-bags-dance.md, package.json, pnpm-lock.yaml, src/blocks/types/result.ts, src/blocks/utilities/array-sum.ts, src/blocks/utilities/lines.ts, src/blocks/utilities/map-to-array.ts, src/blocks/utilities/pad.ts, src/blocks/utilities/strip-ansi.ts, src/commands/diff.ts, src/utils/diff.ts
Now when there is a single line change `diff` switches to a char diff of that line.
=> feat: `diff` command char diffs on single line changes

.changeset/orange-ducks-compare.md, packages/cli/src/utils/language-support.ts, packages/cli/src/utils/parse-package-name.ts
=> fix: `build` can now understand complex paths

.changeset/selfish-zebras-warn.md, .github/workflows/ci.yml, .github/workflows/pkg-pr-new.yml, .github/workflows/publish.yaml, package.json, packages/cli/package.json, packages/cli/src/commands/add.ts, pnpm-lock.yaml
- Fixes issue where subdeps could be added twice
- Adds pkg.pr.new previews to PRs
=> fix: duplicate adds

.changeset/metal-maps-smash.md
=> chore: add changeset

packages/cli/package.json, sites/docs/src/lib/components/site/docs/sub-heading.svelte, sites/docs/src/lib/ts/on-this-page.ts, sites/docs/src/routes/docs/+layout.svelte, sites/docs/src/routes/docs/setup/registry/+page.svelte
The `on this page` could use support for sub-subheadings too but I can do that when there are sub-subheadings on the site lol
=> docs: Add docs for excluded deps and `on this page`

.changeset/fuzzy-points-allow.md, .changeset/kind-jokes-poke.md, .changeset/seven-hotels-add.md, packages/cli/src/commands/add.ts, packages/cli/src/commands/init.ts, packages/cli/src/commands/update.ts, packages/cli/src/utils/ascii.ts, packages/cli/src/utils/build.ts, sites/docs/src/routes/docs/cli/+page.svelte, sites/docs/src/routes/docs/setup/project/+page.svelte, sites/docs/src/routes/docs/setup/registry/+page.svelte
`init` now helps you setup your build script for your registry. 
- Fixed a bug with warnings in the `build` command
- Fixed a bug where `detect` was using the wrong cwd
=> feat: improved init command

packages/cli/package.json, sites/docs/src/lib/components/site/map.ts, sites/docs/src/routes/docs/jsrepo-json/+page.svelte
=> docs: add docs for jsrepo.json

sites/docs/src/routes/+page.svelte
=> docs: Fix hero centering

pnpm-lock.yaml, sites/docs/src/routes/docs/+page.svelte
- Adds FAQ "Is this trying to replace npm?"
- Fixes broken version in lockfile
=> docs: Add FAQ "Is this trying to replace npm?"

.changeset/tricky-cows-march.md, packages/cli/package.json, packages/cli/src/commands/init.ts
=> fix: Move `package.json` check to the top of `init --registry`

packages/cli/package.json, pnpm-lock.yaml, sites/docs/package.json, sites/docs/src/lib/components/site/header/header.svelte, sites/docs/src/lib/components/ui/github/index.ts, sites/docs/src/lib/components/ui/github/star-button.svelte, sites/docs/src/routes/+layout.server.ts, sites/docs/src/routes/+page.svelte, sites/docs/src/routes/docs/badges/+page.svelte
- Show 1.0.0 in the hero (better for SS)
- Add the ability to copy either the raw url of a badge or a markdown embed
- Add github star count to the header
=> docs: General Improvements

.changeset/mean-waves-refuse.md, packages/cli/src/commands/add.ts, packages/cli/src/commands/test.ts, packages/cli/src/commands/update.ts, packages/cli/src/utils/blocks.ts, packages/cli/src/utils/git-providers.ts, packages/cli/tests/git-providers.test.ts, sites/docs/src/routes/docs/git-providers/+page.svelte, sites/docs/src/routes/docs/git-providers/github/+page.svelte, sites/docs/src/routes/docs/git-providers/gitlab/+page.svelte, sites/docs/src/routes/docs/jsrepo-json/+page.svelte, sites/docs/src/routes/docs/private-repositories/+page.svelte, sites/docs/src/routes/docs/setup/registry/+page.svelte
Working towards #163 
Adds support for gitlab private and public repositories. Full support includes support for branches and tags that should just work on paste.
=> feat: GitLab support 🎉

.changeset/shiny-cycles-impress.md, packages/cli/package.json, packages/cli/src/utils/git-providers.ts
Improves the error message with some reasons why it may have failed.
=> feat: Improve manifest file error message

.changeset/hungry-deers-scream.md, .changeset/spotty-months-accept.md, packages/cli/package.json, packages/cli/src/utils/git-providers.ts, pnpm-lock.yaml
Was getting some infinite hanging behavior before with the built in fetch.
=> feat: use `node-fetch` instead of built in fetch

.changeset/nasty-frogs-kneel.md, .changeset/proud-beans-wash.md, .changeset/slow-timers-run.md, packages/cli/.gitignore, packages/cli/README.md, packages/cli/bin.mjs, packages/cli/package.json, packages/cli/src/index.ts
- Changes exports to use `./dist/index.js` instead of `bin.mjs`
- Update package docs and tags
=> chore: Package documentation and optimization

.changeset/lovely-lions-tan.md, packages/cli/package.json, packages/cli/src/index.ts, packages/cli/tsup.config.ts
Trying to reduce the size of the package to hopefully improve startup times.
=> chore: Reduce package size

packages/cli/package.json, pnpm-lock.yaml, sites/docs/package.json, sites/docs/src/hooks.server.ts, sites/docs/src/routes/+error.svelte
- Custom 404 page
- Reroute `/about` to `/docs/about`
- Bump deps
=> docs: A few improvements

.changeset/gorgeous-parrots-listen.md, .changeset/loud-birds-reply.md, packages/cli/jsrepo.json, packages/cli/package.json, packages/cli/src/commands/init.ts, packages/cli/src/utils/language-support.ts, sites/docs/jsrepo.json, sites/docs/src/app.css, sites/docs/src/routes/+page.svelte, sites/docs/src/routes/docs/jsrepo-json/+page.svelte, sites/docs/src/routes/docs/language-support/+page.svelte
=> feat: Config file formatting

.changeset/swift-needles-love.md, packages/cli/jsrepo.json, packages/cli/package.json, packages/cli/src/commands/init.ts, sites/docs/jsrepo.json
=> fix: Fix issue where custom paths where overwritten when running init for a second time

.changeset/twenty-suits-admire.md, packages/cli/package.json, packages/cli/src/commands/add.ts, packages/cli/src/utils/prompts.ts
Fixes #243 
Now when adding blocks we fetch their content concurrently. So you should see a big improvement if you are installing many blocks at once.
Also fixes #242
=> perf: Concurrently fetch blocks

.changeset/olive-rice-play.md, packages/cli/package.json, packages/cli/src/commands/build.ts, sites/docs/src/routes/docs/cli/+page.svelte, sites/docs/src/routes/docs/git-providers/bitbucket/+page.svelte, sites/docs/src/routes/docs/git-providers/github/+page.svelte, sites/docs/src/routes/docs/git-providers/gitlab/+page.svelte, sites/docs/src/routes/docs/setup/project/+page.svelte
Fixes issue with `--do-not-list` flags on `build` command. Ships some docs fixes.
=> fix: Fix `--do-not-list` flags

.changeset/strong-shirts-run.md, packages/cli/package.json, packages/cli/src/commands/init.ts
I'm actually 0x I just fix my own mistakes all day.
=> fix: Incorrect `$schema` being applied during registry `init`

.changeset/wise-points-report.md, packages/cli/package.json, packages/cli/src/commands/add.ts
Now you can provide a formatter when using zero config adds
=> feat: Add formatter prompt to zero-config `add`

.changeset/three-buses-tan.md, packages/cli/package.json, packages/cli/src/commands/add.ts, packages/cli/src/utils/prompts.ts
=> feat: Add overwrite-all prompt to `add` command

.changeset/big-pears-perform.md, packages/cli/package.json, packages/cli/src/commands/add.ts
=> feat: Add the ability to specify a path for each category when adding without a config

.changeset/eleven-sloths-invent.md, .changeset/violet-tables-smile.md, examples/project/pnpm-lock.yaml, packages/cli/package.json, packages/cli/src/commands/add.ts, pnpm-lock.yaml, sites/docs/package.json
Fixes #286 
- Also fixes an issue where you could be prompted multiple times for the directory for the same category
=> fix: `-y, --y` flag doesn't skip zero-config confirmation prompt

packages/cli/package.json, sites/docs/src/routes/demos/+page.svelte, sites/docs/src/routes/docs/registries/+page.svelte
Thanks to @shyakadavis for allowing Geist to be included on the registries list!
=> docs: Another demo + add Geist to the registry list

sites/docs/src/app.css, sites/docs/src/lib/components/ui/button/button.svelte, sites/docs/src/lib/components/ui/button/index.ts, sites/docs/src/lib/components/ui/code/code.svelte, sites/docs/src/lib/components/ui/code/copy.svelte, sites/docs/src/lib/components/ui/code/index.ts, sites/docs/src/lib/components/ui/code/langs.ts, sites/docs/src/lib/components/ui/code/shiki-provider.svelte, sites/docs/src/lib/utils/context-provider.ts, sites/docs/src/lib/utils/utils.ts, sites/docs/src/routes/docs/git-providers/azure-devops/+page.svelte, sites/docs/src/routes/docs/git-providers/bitbucket/+page.svelte, sites/docs/src/routes/docs/git-providers/github/+page.svelte, sites/docs/src/routes/docs/git-providers/gitlab/+page.svelte, sites/docs/src/routes/docs/jsrepo-build-config-json/+page.svelte, sites/docs/src/routes/docs/jsrepo-json/+page.svelte
Fixes formatting in some code snippets as well.
=> docs: Update code component

packages/cli/package.json, sites/docs/src/routes/+layout.svelte
Ensure `<Sidebar.Trigger/>` appears on demo and home screens on mobile.
=> docs: Fix sidebar navigation

.changeset/old-geckos-think.md, packages/cli/package.json, pnpm-lock.yaml, sites/docs/package.json, sites/docs/src/routes/demos/+page.svelte
- Fix demos layout
- Update dependencies
- Update dependencies
=> docs: Fix docs demos layout

.changeset/early-roses-relax.md, .changeset/shaggy-doors-agree.md, package.json, packages/cli/package.json, packages/cli/scripts/generate-docs.ts, packages/cli/src/cli.ts, packages/cli/src/commands/add.ts, packages/cli/src/commands/auth.ts, packages/cli/src/commands/build.ts, packages/cli/src/commands/diff.ts, packages/cli/src/commands/exec.ts, packages/cli/src/commands/init.ts, packages/cli/src/commands/test.ts, packages/cli/src/commands/update.ts, packages/cli/src/index.ts, pnpm-lock.yaml, sites/docs/package.json, sites/docs/src/lib/components/site/header.svelte, sites/docs/static/docs/cli/llms.txt, sites/docs/static/llms.txt
Adds `llms.txt` and `/docs/cli/llms.txt` hopefully this can help improve AI responses.
- Add description to `add`, `exec`, and `update` commands
- Move files to make documentation generation possible
=> docs: Add llms.txt

.changeset/green-turkeys-wave.md, packages/cli/package.json, packages/cli/src/cli.ts, packages/cli/src/commands/add.ts, packages/cli/src/commands/auth.ts, packages/cli/src/commands/build.ts, packages/cli/src/commands/diff.ts, packages/cli/src/commands/exec.ts, packages/cli/src/commands/init.ts, packages/cli/src/commands/test.ts, packages/cli/src/commands/update.ts, packages/cli/src/index.ts, packages/cli/src/utils/blocks/utils/pad.ts, packages/cli/src/utils/blocks/utils/strip-ansi.ts, packages/cli/src/utils/context.ts, packages/cli/src/utils/get-latest-version.ts, packages/cli/src/utils/prompts.ts, pnpm-lock.yaml
Now when a users CLI is out of date they will get a message to update with steps to do so.
- Also bumps deps
=> feat: new version available message

.changeset/hip-geckos-wink.md, packages/cli/package.json, packages/cli/src/utils/language-support.ts, packages/cli/tests/build.test.ts, packages/cli/tests/language-support.test.ts
Fixes #354
Improves build test case to ensure we catch this in the future.
=> fix: Fix an issue where aliases with extensions could cause the builds to fail

.changeset/modern-tips-boil.md, packages/cli/package.json, packages/cli/src/utils/build/index.ts, packages/cli/tests/build.test.ts, sites/docs/src/lib/components/ui/video-player/video-player.svelte
=> fix: Ensure ignores work correctly

.changeset/calm-meals-relate.md, .changeset/sixty-keys-give.md, .changeset/sour-turtles-beg.md, packages/cli/package.json, packages/cli/src/commands/add.ts, packages/cli/src/commands/test.ts, packages/cli/src/commands/update.ts, packages/cli/src/utils/blocks.ts, packages/cli/src/utils/blocks/utils/url.ts, packages/cli/src/utils/config.ts, packages/cli/src/utils/prompts.ts, packages/cli/src/utils/providers.ts, packages/cli/tests/add.test.ts, pnpm-lock.yaml
- When resolving repo paths and fetching the manifest run in parallel
- Fix some issues with box text wrapping by using `boxen`
- Abstract logic for resolving block paths and add a test case
- bump deps
=> fix: General CLI improvements

sites/docs/src/lib/ts/markdown.ts, sites/docs/src/lib/ts/registry/index.ts
Edge functions are timing out and I really don't know why...
=> revert server side changes

pnpm-lock.yaml, sites/docs/package.json, sites/docs/src/lib/ts/markdown.ts, sites/docs/src/routes/registry/registry.svelte
I really hope that serverless functions like this better. It works better locally.
=> feat(docs): Add-back shiki with fine grained bundle

packages/cli/package.json, sites/docs/src/lib/components/ui/code/code.svelte
- This works differently between dev and prod
=> fix(docs): Fix border around code blocks

.changeset/loud-lies-double.md, packages/cli/package.json, packages/cli/src/utils/registry-providers/index.ts, sites/docs/src/lib/components/site/header.svelte, sites/docs/src/lib/components/ui/github/star-button.svelte, sites/docs/src/lib/ts/registry/index.ts, sites/docs/src/routes/+layout.server.ts, sites/docs/src/routes/+page.server.ts, sites/docs/src/routes/+page.svelte
Using the nice SvelteKit APIs I am now doing what we should've been doing from the beginning. There should be a noticable difference to load times.
=> docs: Improve homepage load times by streaming data

.changeset/rotten-meals-film.md, packages/cli/package.json, packages/cli/src/commands/init.ts, pnpm-lock.yaml
=> fix: Fix install dependencies prompt on registry init

.changeset/wicked-teeth-create.md, packages/cli/package.json, packages/cli/src/utils/registry-providers/internal.ts
Thanks for catching this @shhdharmen!
=> fix: ensure getProviderToken reads from registry origin

.changeset/sweet-parents-attack.md
=> chore: changeset

pnpm-lock.yaml, sites/docs/package.json, sites/docs/src/routes/api/registries/+server.ts
You can now provide an `order_by` parameter to order either alphabetically or by popularity. 
- updates the query to be `%<query>%` instead of `<query>%`
- bumps deps
=> feat(site): improve sorting

README.md
This idea is gold, but I almost dismissed it because I didn't understand it. It only clicked for me when I read https://jsrepo.dev/docs, so I copied the text and pasted in the README.
Feel free to dismiss my PR
=> Add more details in the README

.changeset/happy-plums-tickle.md, .changeset/mean-seals-shine.md, package.json, pnpm-lock.yaml, src/utils/registry-providers/github.ts
Fixes #534 
This should help us save quite a bit on the bundle. Still lots of work to do but it's a start.
=> chore: remove octokit

.changeset/brown-masks-smell.md, .changeset/slimy-seas-train.md, package.json, pnpm-lock.yaml, src/commands/exec.ts, src/commands/test.ts, src/utils/dependencies.ts, src/utils/language-support/svelte.ts, tests/add.test.ts, tests/build.test.ts, tests/providers.test.ts
- prettier-plugin-svelte (idk why this was here tbh)
- use `tinyexec` instead of `execa`
=> chore: bundle mending

.changeset/dull-trams-yawn.md, package.json, schemas/registry-config.json, src/commands/publish.ts, src/types.ts, src/utils/config.ts, src/utils/manifest.ts, src/utils/registry-providers/jsrepo.ts
Allows you to configure registry access from the build config file for jsrepo.com marketplace support.
=> feat: jsrepo.com Marketplace support

.changeset/common-badgers-fly.md, src/utils/mcp.ts
- `list-components` - More concise responses
- `list-components` - Better examples
- Rename `discover-registries` -> `search-registries` to make it more clear the function
- `search-registries` - Allow ai to add a search query
=> feat(mcp): Even more optimizations and improvements
