jsrepojs/jsrepo

- .changeset/soft-melons-marry.md
- README.md
- bin.mjs
- biome.json
- blocks/utilities/array-to-map.ts
- blocks/utilities/map-to-array.ts
- blocks/utilities/truncate.ts
- build.config.ts
- package.json
- schema.json
- src/blocks.ts
- src/commands/add.ts
- src/commands/index.ts
- src/commands/init.ts
- src/config/index.ts
- src/index.ts
- Adds schema file from **unpkg** cdn.
- Adds better biome rules
> fix: Now correctly uses `$schema` file

- .changeset/tricky-pandas-promise.md
- blocks/types/result.test.ts
- blocks/types/result.ts
- blocks/utilities/sleep.test.ts
- package.json
Adds `match` and `unwrap` error helper methods to `result`
> feat: Add `match` and `unwrap` methods to `result`

- .changeset/ten-crabs-repeat.md
- blocks/utilities/pad.test.ts
- blocks/utilities/pad.ts
- blocks/utilities/sleep.test.ts
- package.json
- src/blocks.ts
Adds `leftPad` and `rightPad` functions to the `pad.ts` file
> feat: Add `pad` for left and right pad utilities

- .changeset/friendly-bags-film.md
- .changeset/lovely-comics-try.md
- .changeset/tough-gifts-hunt.md
- blocks/utilities/dispatcher.test.ts
- blocks/utilities/dispatcher.ts
- package.json
- pnpm-lock.yaml
- schema.json
- src/blocks.ts
- src/commands/add.ts
- src/commands/init.ts
- src/config/index.ts
The dispatcher block is nice because I have often found myself writing that same thing multiple times much easier to condense it into a reusable block like this.
- Also adds `Deno` support by adding an `imports` option to the config that will control the `.ts` suffix on the re-exports in the generated index file.
- Changes default value on initialization for `includeTests` to false
> feat: Dispatcher block

- .changeset/pre.json
- .changeset/tough-crabs-jump.md
- package.json
- src/utils/build.ts
- src/utils/dependencies.ts
ensures build command doesn't add files in the same subdir to local dependencies.
> fix: `build` command

- .changeset/pre.json
- .github/workflows/ci.yml
- blocks.json
- package.json
- schema.json
- src/commands/init.ts
- src/config/index.ts
- tsconfig.json
This really has already been deprecated but now its officially gone. It hasn't done anything since `includeIndexFile` was removed.
I don't think this one will come back as you would need to implement a way of changing imports for each language and that doesn't really seem practical at the moment.
> BREAKING: deprecate `imports` config option 

- .changeset/dirty-wasps-melt.md
- .changeset/hip-turtles-design.md
- .changeset/red-bottles-worry.md
- packages/cli/package.json
- packages/cli/src/commands/build.ts
- packages/cli/src/utils/build.ts
- packages/cli/src/utils/language-support.ts
- pnpm-lock.yaml
- sites/docs/src/routes/docs/cli/+page.svelte
- sites/docs/src/routes/docs/language-support/+page.svelte
- Adds support for `*.vue` files.
- Exempts `svelte` and `vue` from being added as dependencies of `*.svelte` and `*.vue` files. I think we can safely assume anyone installing those files should already have those installed.
- Adds `--exclude-deps` flag to the `build` command. This allows you to prevent certain dependencies from being added to the manifest. This is nice when you have a library that uses `next` or something and want to make sure `next` isn't installed when others bring your code into their next project.
> feat: vue support 🎉

- .changeset/soft-chicken-yawn.md
- packages/cli/package.json
- packages/cli/src/commands/add.ts
- packages/cli/src/commands/build.ts
- packages/cli/src/commands/diff.ts
- packages/cli/src/commands/init.ts
- packages/cli/src/commands/test.ts
- packages/cli/src/commands/update.ts
- packages/cli/src/index.ts
- packages/cli/src/utils/blocks.ts
- packages/cli/src/utils/build.ts
- packages/cli/src/utils/config.ts
- packages/cli/src/utils/language-support.ts
- packages/cli/src/utils/package.ts
- pnpm-lock.yaml
Should make the experience more pleasant for any unfortunate windows users like myself.
> chore: Use `pathe` instead of `node:path` 

- .changeset/stale-buttons-cross.md
- .changeset/tough-apples-attend.md
- .changeset/tricky-files-taste.md
- packages/cli/package.json
- packages/cli/src/commands/build.ts
- packages/cli/src/utils/build.ts
- sites/docs/src/routes/docs/cli/+page.svelte
Fixes #145 
- Also adds `--error-on-warn` flag that will cause build to error on warnings
- jsrepo now checks your manifest file before writing it so it can warn you about dependencies to blocks that don't exist and remote dependencies that aren't using pinned versions.
> feat: `build` flags `--include-blocks` and `--include-categories`

- .changeset/polite-suns-sleep.md
- .changeset/popular-kids-behave.md
- packages/cli/package.json
- packages/cli/src/commands/add.ts
- packages/cli/src/commands/auth.ts
Fixes #112 
Enables zero-config adds.
This way you can tell your users to install your code with:
```bash
npx jsrepo add github/ieedan/std/utils/math
```
And it will just work out of the box.
- Also improves `--logout` in `auth` command
> feat: zero-config adds

- .changeset/gold-lemons-juggle.md
- packages/cli/package.json
- packages/cli/src/commands/add.ts
- packages/cli/src/commands/test.ts
- packages/cli/src/utils/blocks.ts
- packages/cli/src/utils/git-providers.ts
- packages/cli/tests/git-providers.test.ts
- sites/docs/src/routes/docs/git-providers/+page.svelte
- sites/docs/src/routes/docs/git-providers/bitbucket/+page.svelte
- sites/docs/src/routes/docs/private-repositories/+page.svelte
- sites/docs/src/routes/docs/setup/registry/+page.svelte
Fixes #163 
Adds full bit bucket support including tags and branches. Private repositories *should* work I am using the Bearer scheme like there is in the docs but if there are any paying users that would like to test that for me please do!
> feat: BitBucket support 🎉

- .changeset/rude-tools-trade.md
- packages/cli/package.json
- packages/cli/src/commands/add.ts
- packages/cli/src/commands/update.ts
- packages/cli/src/utils/package.ts
- sites/docs/src/hooks.client.ts
Fixes #171 
Previously we just installed all dependencies no matter what if the user said yes. Now we are only ever going to install what we need based on what's currently in the `package.json`.
> fix: Check `package.json` before installing dependencies

- packages/cli/package.json
- packages/cli/src/utils/git-providers.ts
If a branch is not supplied to github the it will be fetched using octokit.
> feat: Detect `github` default branch

- .changeset/eighty-numbers-stare.md
- .changeset/good-socks-return.md
- .changeset/quiet-cherries-decide.md
- .changeset/twelve-garlics-peel.md
- packages/cli/package.json
- packages/cli/src/commands/add.ts
- packages/cli/src/commands/update.ts
- packages/cli/src/utils/blocks.ts
- packages/cli/src/utils/git-providers.ts
- Only install vitest when blocks actually have tests
- Use `<category>/<name>` in resolveTree as the key
- Use `<category>/<name>` when asking if you'd like to overwrite the blocks
> fix: General fixes

- .changeset/real-crabs-rush.md
- packages/cli/package.json
- packages/cli/src/utils/git-providers.ts
- sites/docs/src/routes/docs/git-providers/bitbucket/+page.svelte
- sites/docs/src/routes/docs/git-providers/github/+page.svelte
- sites/docs/src/routes/docs/git-providers/gitlab/+page.svelte
GitHub already does this I just hadn't added it to the other GitLab and BitBucket yet. 
So now when using `gitlab/ieedan/std` or `bitbucket/ieedan/std` it won't just point to a hard coded default branch `main` and `master` but will instead lookup the default branch and point to that.
> feat: Autodetect default branches for git providers

- .changeset/eight-news-beg.md
- packages/cli/package.json
- packages/cli/src/commands/init.ts
> feat: When adding a new repo with `init` preconfigured paths should default to their configured value

- .changeset/dull-spies-wink.md
- .changeset/sixty-bears-serve.md
- packages/cli/package.json
- packages/cli/src/utils/language-support.ts
- sites/docs/src/lib/components/icons/index.ts
- sites/docs/src/lib/components/icons/svg.svelte
- sites/docs/src/routes/docs/language-support/+page.svelte
Previously if you had an import to the category root like `$lib/assets/icons` jsrepo would just crash because there would be no block specifier. Now it resolves that path to `$lib/assets/icons/index` as is consistent with JS expected behavior.
- Add `*.svg` support
> fix: Resolve paths to category root to an `index` block 

- .changeset/eighty-cooks-sin.md
- .changeset/young-experts-clean.md
- packages/cli/package.json
- packages/cli/src/commands/add.ts
- packages/cli/src/commands/diff.ts
- packages/cli/src/commands/init.ts
- packages/cli/src/commands/update.ts
- packages/cli/src/utils/blocks.ts
- packages/cli/src/utils/git-providers.ts
For some reason we would re-fetch info about each repo for every block. This never should have been the case. This fixes it so that we get the info once at the beginning and then never again.
> perf: Improve performance when resolving blocks

- .changeset/healthy-balloons-perform.md
- .changeset/hungry-cups-beg.md
- examples/registry/jsrepo-build-config.json
- examples/registry/src/types/index.ts
- packages/cli/package.json
- packages/cli/schemas/registry-config.json
- packages/cli/src/commands/build.ts
- packages/cli/src/commands/init.ts
- packages/cli/src/utils/ascii.ts
- packages/cli/src/utils/build/check.ts
- packages/cli/src/utils/build/index.ts
- packages/cli/src/utils/config.ts
- packages/cli/src/utils/language-support.ts
- sites/docs/src/routes/docs/jsrepo-build-config-json/+page.svelte
Fixes #248 
- Converts the current rules into eslint-style configurable rules.
- Adds a few helpful rules `max-local-dependencies` and `no-category-index-file-dependency` that should help warn of common pitfalls
- Removes `output` and `errorOnWarn` config options since they no longer do anything
> feat: Improve post build manifest validation

- .changeset/dirty-jars-film.md
- .changeset/great-rules-sort.md
- .changeset/quick-terms-lay.md
- packages/cli/package.json
- packages/cli/schemas/registry-config.json
- packages/cli/src/commands/build.ts
- packages/cli/src/utils/build/check.ts
- packages/cli/src/utils/build/index.ts
- packages/cli/src/utils/config.ts
- sites/docs/src/routes/docs/cli/+page.svelte
- sites/docs/src/routes/docs/jsrepo-build-config-json/+page.svelte
- Blocks that are not listed and not depended on by any other blocks are essentially 'dead' code that just bloats the manifest so now we remove them during the build
- Adds a `no-unused-block` rule that can be used to detect blocks that will be removed during build
- Adds a `preview` key to the build config to allow you to see what the blocks list will look like when the user runs `jsrepo add`
> feat: prune blocks, new rule, and add preview

- .changeset/heavy-birds-shake.md
- packages/cli/package.json
- packages/cli/src/commands/add.ts
- packages/cli/src/utils/persisted.ts
Fixes #270 
Now when you add with no config your selections will be remembered for the next time you run jsrepo in that same directory.
> feat: Remember `zero-config` options

- .changeset/seven-singers-carry.md
- .changeset/wicked-moons-rest.md
- examples/registry/jsrepo-build-config.json
- examples/registry/jsrepo-manifest.json
- packages/cli/package.json
- packages/cli/schemas/registry-config.json
- packages/cli/src/commands/build.ts
- packages/cli/src/commands/init.ts
- packages/cli/src/utils/build/check.ts
- packages/cli/src/utils/build/index.ts
- packages/cli/src/utils/config.ts
- sites/docs/src/routes/docs/cli/+page.svelte
- sites/docs/src/routes/docs/jsrepo-build-config-json/+page.svelte
Fixes #274
Fixes #273 
- Adds `no-framework-dependency` rule with some initially configured frameworks
- Adds `excludeBlocks` and `excludeCategories` keys to config
> feat: `no-framework-dependency` rule and `excludeBlocks` / `excludeCategories`

- .changeset/tall-rocks-pay.md
- packages/cli/src/utils/language-support.ts
Found this working on `shadcn-svelte`.
> feat: ensure `<script module>` in `*.svelte` files is walked for dependencies

- .changeset/cuddly-files-bathe.md
- .changeset/early-spies-shave.md
- packages/cli/package.json
- packages/cli/src/utils/build/check.ts
- packages/cli/src/utils/language-support.ts
- ensure `build` returns the error when the extended tsconfig doesn't exist.
- fix stack overflow when checking for circular dependencies.
> fix: Resolve a few bugs with `build`

- .changeset/ninety-pets-shave.md
- packages/cli/package.json
- packages/cli/schemas/registry-config.json
- packages/cli/src/commands/build.ts
- packages/cli/src/commands/init.ts
- packages/cli/src/utils/build/index.ts
- packages/cli/src/utils/config.ts
- sites/docs/src/routes/docs/cli/+page.svelte
- sites/docs/src/routes/docs/jsrepo-build-config-json/+page.svelte
The `listBlocks` and `listCategories` build config keys give you more fine grained control over what exactly the user sees when running add.
> feat: `listBlocks` and `listCategories` config keys

- .changeset/plenty-penguins-invent.md
- examples/registry/jsrepo-manifest.json
- examples/registry/src/components/button.svelte
- packages/cli/package.json
- packages/cli/src/utils/language-support.ts
Previously we only resolved dependencies that came from imports. This PR adds the ability for us to resolve modules that are used in `re-exports`.
> feat: Resolve `re-exported` dependencies

- .changeset/late-cows-give.md
- packages/cli/package.json
- packages/cli/src/utils/build/index.ts
Unfortunately I didn't realize everything this would effect. I still want to make this happen but it's going to take more work so I will just revert it in the mean time.
> fix: Revert change to `.svelte.(js|ts)` block names

- .changeset/unlucky-avocados-bake.md
- packages/cli/package.json
- packages/cli/src/commands/exec.ts
- packages/cli/src/commands/index.ts
- packages/cli/src/index.ts
- packages/cli/src/utils/blocks/package-managers/flags.ts
- packages/cli/src/utils/dependencies.ts
- pnpm-lock.yaml
- sites/docs/src/routes/docs/cli/+page.svelte
Aims to close #315 
Makes it possible to run code from a jsrepo registry using the newly added `exec` (`x`) command. The result looks something like:
```bash
jsrepo exec github/ieedan/scripts/general/hello -- Aidan
┌   jsrepo  v1.22.2 
│
◇  Retrieved scripts from github/ieedan/scripts
│
◇  Added general/hello
Hello Aidan!
```
The alias `x` can also be used:
```bash
jsrepo x github/ieedan/scripts/general/hello
```
You use `--` to pass args to the script:
```bash
jsrepo exec github/ieedan/scripts/general/hello -- Aidan
```
You can only run a single script at a time but you can choose which script to run when running in the root of a project initialized with jsrepo or by passing the `--repo` flag.
```bash
jsrepo exec --repo github/ieedan/scripts
```
As of now there are no code changes …
> feat: Add `exec` (`x`) command

- .changeset/young-monkeys-smile.md
- packages/cli/package.json
- packages/cli/src/commands/test.ts
Fixes #325 
This was a frustrating one as it was something to do with the way that execa was parsing the raw string command. 
In any case it should've been setup this way from the beginning.
> fix: Fix `test` command on linux

- .changeset/real-waves-smile.md
- .changeset/thick-fans-bathe.md
- examples/registry/blocks/svelte/component.svelte
- examples/registry/blocks/svelte/test.js
- examples/registry/blocks/svelte/test.svelte.ts
- examples/registry/jsrepo-manifest.json
- examples/registry/tsconfig.json
- packages/cli/package.json
- packages/cli/src/utils/language-support.ts
- pnpm-lock.yaml
Fixes #340 
Previously if you had a file `bar.svelte.ts` you had to add the `.js / .ts` extension on the end of your import for `jsrepo` to correctly resolve it.
This PR fixes the resolution so that you can simply import from `bar.svelte` instead of `bar.svelte.js`.
For an example of this issue you can see: 
https://github.com/ieedan/shadcn-svelte-extras/blob/main/src/lib/components/ui/chat/chat-list.svelte#L7
> fix: Ensure local dependencies are resolved correctly when files are named like `bar.svelte.ts`

- .changeset/funny-schools-mate.md
- packages/cli/package.json
- packages/cli/src/commands/add.ts
- packages/cli/src/commands/init.ts
- packages/cli/src/commands/update.ts
- packages/cli/src/utils/dependencies.ts
Fixes an issue with yarn. This might help speed up installs too so that would be cool.
> fix: Use `add` instead of `install` for `package-manager-detector` when installing dependencies

- .changeset/happy-chairs-suffer.md
- packages/cli/package.json
- packages/cli/src/utils/blocks.ts
- packages/cli/src/utils/providers.ts
- packages/cli/src/utils/url.ts
Previously when resolving raw urls the `new URL()` constructor incorrectly handling urls that don't have a trailing slash. 
I think this is a pretty stupid behavior but basically it does this:
```ts
new URL('test.js', 'https://x.com/default'); // -> https://x.com/test.js
new URL('test.js', 'https://x.com/default/'); // -> https://x.com/default/test.js
```
This PR adds the trailing slash when we parse the url to ensure that it is handled correctly.
> fix: Ensure urls with or without a trailing slash are treated the same

- .changeset/two-tigers-train.md
- packages/cli/package.json
- packages/cli/src/commands/build.ts
- packages/cli/src/utils/build/index.ts
- packages/cli/tests/build.test.ts
- pnpm-lock.yaml
Fixes #367 
Previously we wouldn't ignore any folders when building now we look at the .gitignore to determine if any directories shouldn't be built.
We also automatically ignore the following directories `.git`, and `node_modules`.
> feat: Respect .gitignore

- .changeset/thin-zoos-confess.md
- packages/cli/package.json
- packages/cli/src/registry/index.ts
- packages/cli/tsup.config.ts
This will provide the basic types needed for working with the manifest and config files. Could be useful for any sort of tooling build around jsrepo.
> feat: Expose registry types

- .changeset/breezy-papayas-grab.md
- .changeset/lazy-coins-admire.md
- packages/cli/package.json
- packages/cli/src/commands/init.ts
- packages/cli/src/utils/registry-providers/http.ts
- packages/cli/src/utils/registry-providers/index.ts
- packages/cli/tests/providers.test.ts
Fixes https://github.com/DavidHDev/react-bits/issues/39
- Improve error given when `JSON.parse` fails in `fetchManifest`
- Add test cases
This was caused because the `URL` api is dumb.
> fix: prevent urls from being cut short in http provider

- .changeset/itchy-cycles-taste.md
- examples/registry/jsrepo-build-config.json
- examples/registry/jsrepo-manifest.json
- packages/cli/jsrepo.json
- packages/cli/package.json
- packages/cli/schemas/registry-config.json
- packages/cli/src/commands/build.ts
- packages/cli/src/utils/build/index.ts
- packages/cli/src/utils/config.ts
- packages/cli/src/utils/language-support.ts
- packages/cli/tests/build.test.ts
- packages/cli/tests/utils.ts
- pnpm-lock.yaml
- sites/docs/src/routes/docs/cli/build/+page.svelte
- sites/docs/src/routes/docs/jsrepo-build-config-json/+page.svelte
- sites/docs/static/docs/cli/llms.txt
Fixes #399 
Adds an `allowSubdirectories` config key that enables building blocks that contain subdirectories.
This allows for structures like:
```ts
root
├── ...
└── <category>
└── <block>
├── <folder>
│	└── <file>
└── <file>
```
- Bump dependencies
- Update local dependency resolution
- Had to do this since before there wasn't any way to tell if an import was self referencing but now we know
- Slightly refactor build
- Update build tests
> feat: Subdirectories

- sites/docs/src/lib/components/site/docs/jsrepo.svelte
- sites/docs/src/lib/components/site/docs/link.svelte
- sites/docs/src/lib/components/site/header.svelte
- sites/docs/src/lib/components/ui/snippet/jsrepo-snippet.svelte
- sites/docs/src/lib/components/ui/snippet/snippet.svelte
- sites/docs/src/routes/docs/+layout.svelte
Fixes #398 
For all you light mode psychopaths... (JK)
> fix(docs): Use `text-foreground` instead of `text-primary` in light mode

- .changeset/cuddly-comics-hammer.md
- .changeset/famous-hotels-film.md
- .changeset/great-bobcats-hunt.md
- .changeset/many-geese-thank.md
- packages/cli/package.json
- packages/cli/src/commands/init.ts
- packages/cli/src/utils/blocks/ts/strings.ts
- packages/cli/src/utils/config.ts
- packages/cli/src/utils/files.ts
- packages/cli/src/utils/language-support.ts
- sites/docs/jsrepo.json
Fixes #420 
Fixes #421 
- Improves error messages when path aliases are incorrect
- Prevent inputting invalid path for default blocks path on `init`
- Autofix incorrect file extensions on config files that are js descendents
+ a little code cleanup
> feat(cli): ux improvements

- .changeset/tricky-humans-fold.md
- packages/cli/package.json
- packages/cli/schemas/project-config.json
- packages/cli/schemas/registry-config.json
- packages/cli/src/commands/build.ts
- packages/cli/src/commands/init.ts
- packages/cli/src/types.ts
- packages/cli/src/utils/build/check.ts
- packages/cli/src/utils/build/index.ts
- packages/cli/tests/build.test.ts
Fixes #424 
With this PR config files can now have remote dependencies which is really nice if you are using custom plugins in your config files, the dependencies will be installed on init.
> feat: Include remote dependencies for config files 🎉

- .changeset/eight-moons-drop.md
- packages/cli/package.json
- packages/cli/src/cli.ts
- packages/cli/src/commands/add.ts
- packages/cli/src/commands/auth.ts
- packages/cli/src/commands/build.ts
- packages/cli/src/commands/exec.ts
- packages/cli/src/commands/init.ts
- packages/cli/src/commands/test.ts
- packages/cli/src/commands/update.ts
- packages/cli/src/utils/context.ts
- packages/cli/src/utils/get-latest-version.ts
- packages/cli/src/utils/get-watermark.ts
- packages/cli/src/utils/package.ts
- packages/cli/src/utils/prompts.ts
- packages/cli/src/utils/registry-providers/azure.ts
- packages/cli/src/utils/registry-providers/bitbucket.ts
- packages/cli/src/utils/registry-providers/github.ts
- packages/cli/src/utils/registry-providers/gitlab.ts
- packages/cli/src/utils/registry-providers/internal.ts
- packages/cli/tsup.config.ts
- pnpm-lock.yaml
- sites/docs/static/docs/cli/llms.txt
- cache registry provider state (except for http) to improve manifest fetch times
- remove some unnecessary code running before startup
> feat: Performance improvements

- .changeset/curvy-ducks-draw.md
- .changeset/four-doors-matter.md
- .changeset/thin-fireants-clean.md
- packages/cli/src/commands/init.ts
- packages/cli/src/commands/update.ts
- packages/cli/src/utils/ai.ts
- packages/cli/src/utils/files.ts
- packages/cli/src/utils/prompts.ts
- sites/docs/src/lib/components/ui/copy-button/copy-button.svelte
- sites/docs/static/docs/cli/llms.txt
- Add `Additional instructions:` prompt to allow for describing the changes you want when updating a file with an LLM
- Add the ability to iterate on a file change when updating with AI. This will give the AI the chat history as you iterate with it
- Provide your last model choice as the default for the select model prompt
- Consolidate logic for update file
> feat: Add `additional instructions` prompt to `✨ Update with AI ✨`

- packages/cli/package.json
- packages/cli/src/utils/prompts.ts
- pnpm-lock.yaml
We're having an internal debate right now about removing `detectSync` in favor of `detect` so that we don't have to distribute both versions. I'm proactively sending you a PR to avoid you having to do any work on your side in case that happens (still unclear if it will)
> chore: use async version of detect

- .changeset/heavy-dingos-create.md
- .github/workflows/pkg-pr-new.yml
- packages/cli/package.json
- packages/cli/src/utils/registry-providers/gitlab.ts
- packages/cli/src/utils/registry-providers/index.ts
- packages/cli/tests/providers.test.ts
- sites/docs/src/routes/docs/git-providers/gitlab/+page.svelte
Fixes #492 
This adds a `gitlab:` prefix to allow you to specify a self hosted gitlab instance. 
For example if you hosted your gitlab instance at `https://example.com`:
```
gitlab:https://example.com/ieedan/std
```
> feat: Enable usage of self hosted gitlab registries with the `gitlab:` prefix

- .changeset/funny-lights-ask.md
- packages/cli/package.json
- packages/cli/src/utils/language-support/svelte.ts
- pnpm-lock.yaml
This PR includes `prettier-plugin-svelte` so that you can use `--cwd` with `.svelte` files. Previously prettier would try and load `prettier-plugin-svelte` from the current working directory.
Also bumps deps
> fix: Ensure Svelte files can be formatted when using `--cwd`

- .changeset/heavy-llamas-lie.md
- packages/cli/package.json
- packages/cli/src/commands/add.ts
- packages/cli/src/commands/test.ts
- packages/cli/src/utils/blocks/ts/promises.ts
Fixes instances where imports would be replaced when not quoted. This would cause issues if your import was for instance `.` where all instances of `.` in the file would become the new import.
> fix: Test command import resolution

- .changeset/hip-friends-hug.md
- packages/cli/package.json
- packages/cli/src/utils/registry-providers/internal.ts
Since entries in the state cache live forever the it only makes sense that the `--no-cache` flag should cause them to be removed to prevent issues where you can never update the cache again.
> fix: Delete outdated cache when using `--no-cache`

- .changeset/clean-mammals-switch.md
- .changeset/hip-lamps-walk.md
- packages/cli/src/commands/add.ts
- packages/cli/src/utils/package.ts
- packages/cli/src/utils/parse-package-name.ts
- packages/cli/tests/add.test.ts
- sites/docs/src/routes/docs/cli/add/+page.svelte
- sites/docs/src/routes/docs/cli/auth/+page.svelte
- sites/docs/src/routes/docs/cli/build/+page.svelte
- sites/docs/src/routes/docs/cli/exec/+page.svelte
- sites/docs/src/routes/docs/cli/init/+page.svelte
- sites/docs/src/routes/docs/cli/test/+page.svelte
- sites/docs/src/routes/docs/cli/update/+page.svelte
- sites/docs/static/docs/cli/llms.txt
From #520 
This was a obvious oversight of mine pretty disappointing. Also never added docs for the new flags. Now you can more easily configure the flags with a true or false value instead of the --no syntax.
> fix: ensure options don't interfere with config

- .changeset/yellow-mammals-type.md
- package.json
- src/utils/language-support/index.ts
- tests/providers.test.ts
Fixes #548 
This is a bit of a hack that warrants some explanation. Previously having multiple nested paths was a bit risky because you could potentially end up resolving to a path that was not the block you were actually referencing. Essentially since the resolution was based on the order of `dirs` in your build config it was hard to tell how things would be resolved.
With this PR we always resolve to the most specific (longest) path. 
Take for example this project structure:
```
root
├── /src
│   └── /lib
│       └── /components
│           └── /ui
└── ...
```
If I have 2 dirs in my build config:
```jsonc
{
"dirs": ["./src/lib", "./src/lib/components"]
}
```
When a block outside of `src/lib` tries to reference `src/lib/components/ui/button` previously jsrepo would immediately match to …
> fix: Always resolve local dependencies to the most specific route

- .changeset/fruity-llamas-wave.md
- src/cli.ts
- src/commands/index.ts
- src/commands/info.ts
- src/utils/blocks/ts/array.ts
This command mimics the `npm info` command and gives useful information to the user about the registry this is used by tools like changesets to determine if a version of a package exists. (Only for registries hosted on jsrepo.com)
> feat: info command

- .changeset/curvy-cloths-wish.md
- schemas/registry-config.json
- src/commands/init.ts
- src/types.ts
- src/utils/config.ts
- src/utils/manifest.ts
Fixes #562 
This PR introduces a `defaultPaths` key to the `jsrepo-build-config.json` file. This allows you to configure default install locations for your categories in users projects. 
For example:
```jsonc
{
"defaultPaths": {
"ui": "$lib/components/ui"
}
}
```
When the user initializes their project and doesn't configure it otherwise the path will be added to their `jsrepo.json` file like so:
```jsonc
{
"paths": {
"ui": "$lib/components/ui"
}
}
```
> feat: Default category paths

- .changeset/stale-kiwis-itch.md
- schemas/project-config.json
- schemas/registry-config.json
- src/commands/add.ts
- src/commands/build.ts
- src/commands/exec.ts
- src/commands/init.ts
- src/commands/publish.ts
- src/types.ts
- src/utils/blocks.ts
- src/utils/build/index.ts
- src/utils/config.ts
- src/utils/mcp.ts
- tests/build.test.ts
Alternative to #538 
Fixes #537 
This PR enables registry owners to include documentation files (*.md, *.mdx) in their registry. This can help users (or llms) with the usage of registry items. Just like tests adding documentations files is opt-in with the `includeDocs` config key.
@Asuniia thank you for your initial work on this I have added you as a co-author on this PR. Also apologies for how long this took!
> feat: Optionally include doc files in registry

- .changeset/puny-plums-refuse.md
- src/utils/language-support/index.ts
Fixes #587 
The code from #552 made the code removed here unnecessary and in fact, incorrect.
> fix: Ensure blocks can resolve blocks built out of a different `dir`

- .changeset/full-flies-decide.md
- src/utils/registry-providers/github.ts
- src/utils/registry-providers/index.ts
> fix: Fix a regression where users couldn't access private github repos

- .changeset/fifty-eggs-cheer.md
- src/commands/init.ts
- src/utils/config.ts
- src/utils/files.ts
- src/utils/language-support/index.ts
- src/utils/tsconfig.ts
Fixes #606 
With this PR users are now able to have tsconfig files that make use of the `references` top level key. In this approach we simply wrap `createPathsMatcher` from `get-tsconfig` and resolve and append any of the paths from referenced tsconfigs to the paths in the base tsconfig before creating the paths matcher just like before.
> fix: Resolve tsconfig references
